services:
  monolith:
    image: juanzapata1241/gestion-proyectos-monolito
    container_name: proyectos-monolito
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${MONGO_URI}
    networks:
      - proyecto-network

  proyecto-microservice-1:
    container_name: proyecto-microservice-1
    image: juanzapata1241/gestion-proyectos-microservicio
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=3001
    networks:
      - proyecto-network

  proyecto-microservice-2:
    container_name: proyecto-microservice-2
    image: juanzapata1241/gestion-proyectos-microservicio
    ports:
      - "3002:3001"
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=3002
    networks:
      - proyecto-network

  load-balancer:
    container_name: load-balancer
    image: load-balancer:v1
    build:
      context: ./balancer
    ports:
      - "5000:80"
    networks:
      - proyecto-network

networks:
  proyecto-network:
